myauth/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from .views import RegisterView


app_name = 'myauth'

urlpatterns = [
    path('login/', 
         LoginView.as_view(template_name='myauth/login.html',
                           redirect_authenticated_user=True), 
         name='login'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
]

recipe_website/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
    path('myauth/', include('myauth.urls', namespace='myauth')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import path
from .views import *


app_name = 'recipes'

urlpatterns = [
    path('', HomeView.as_view(), name='index'),
    # Units
    path('units/', UnitListView.as_view(), name='unit-list'),
    path('units/create/', UnitCreateView.as_view(), name='unit-create'),
    path('units/<int:pk>/update/', UnitUpdateView.as_view(), name='unit-update'),
    path('units/<int:pk>/delete/', UnitDeleteView.as_view(), name='unit-delete'),
    # Categories
    path('categories/', CategoryListView.as_view(), name='category-list'),
    path('categories/create/', CategoryCreateView.as_view(), name='category-create'),
    path('categories/<int:pk>/update/', CategoryUpdateView.as_view(), name='category-update'),
    path('categories/<int:pk>/delete/', CategoryDeleteView.as_view(), name='category-delete'),
    # Ingredients
    path('ingredients/', IngredientListView.as_view(), name='ingredient-list'),
    path('ingredients/create/', IngredientCreateView.as_view(), name='ingredient-create'),
    path('ingredients/<int:pk>/update/', IngredientUpdateView.as_view(), name='ingredient-update'),
    path('ingredients/<int:pk>/delete/', IngredientDeleteView.as_view(), name='ingredient-delete'),
    # Recipes
    path('recipes/', RecipeListView.as_view(), name='recipe-list'),
    path('recipes/create/', RecipeCreateView.as_view(), name='recipe-create'),
    path('recipes/<int:pk>/update/', RecipeUpdateView.as_view(), name='recipe-update'),
    path('recipes/<int:pk>/delete/', RecipeDeleteView.as_view(), name='recipe-delete'),
    path('recipes/<int:pk>/detail/', RecipeDetailView.as_view(), name='recipe-detail'),
    path('recipes/<int:pk>/restore/', recipe_restore, name='recipe-restore'),
]

recipes/models.py
from django.db import models
from django.contrib.auth.models import User


class RecipeManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(is_archived=False)

class Unit(models.Model):
    name = models.CharField(max_length=50, unique=True)

    class Meta:
        verbose_name = "Unit"
        verbose_name_plural = "Units"

    def __str__(self):
        return self.name

class Category(models.Model):
    name = models.CharField(max_length=100, unique=True, db_index=True)
    parent = models.ForeignKey(
        'self',
        null=True,
        blank=True,
        on_delete=models.CASCADE, 
        related_name='subcategories'
    )

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"
        ordering = ['parent__name', 'name']

    def __str__(self):
        return f"{self.parent.name} -> {self.name}" if self.parent else self.name

class Ingredient(models.Model):
    name = models.CharField(max_length=100, unique=True)
    unit = models.ForeignKey(Unit, on_delete=models.CASCADE, related_name='ingredients')

    class Meta:
        verbose_name = "Ingredient"
        verbose_name_plural = "Ingredients"
        ordering = ['name']

    def __str__(self):
        return self.name

class Recipe(models.Model):
    DIFFICULTY_CHOICES = [
        ('easy', 'Easy'),
        ('medium', 'Medium'),
        ('hard', 'Hard')
    ]

    title = models.CharField(max_length=200, unique=True, db_index=True)
    description = models.TextField()
    instructions = models.TextField()
    cooking_time = models.PositiveIntegerField(help_text="Cooking time in minutes", default=1)
    preparation_time = models.PositiveIntegerField(help_text="Preparation time in minutes", default=1)
    difficulty = models.CharField(max_length=20, choices=DIFFICULTY_CHOICES)
    servings = models.PositiveIntegerField()
    category = models.ManyToManyField(Category, related_name='recipes')
    image = models.ImageField(upload_to='recipes/images/', blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='recipes')
    total_time = models.PositiveIntegerField(help_text="Total time in minutes", editable=False)
    is_archived = models.BooleanField(default=False)
    ingredients = models.ManyToManyField(Ingredient, related_name='used_in_recipes', through='RecipeIngredient')

    class Meta:
        verbose_name = "Recipe"
        verbose_name_plural = "Recipes"
        ordering = ['-created_at']

    objects = RecipeManager()
    all_objects = models.Manager()

    def delete(self):
        self.is_archived = True
        self.save()

    def save(self, *args, **kwargs):
        self.total_time = self.preparation_time + self.cooking_time
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

class RecipeIngredient(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, related_name='recipe_ingredients')
    ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE, related_name='ingredient_recipes')
    quantity = models.DecimalField(max_digits=5, decimal_places=2)

    class Meta:
        verbose_name = "Recipe Ingredient"
        verbose_name_plural = "Recipe Ingredients"
        unique_together = ['recipe', 'ingredient']

    def __str__(self):
        return f"{self.quantity} {self.ingredient.unit.name} of {self.ingredient.name}"


class FavoriteRecipe(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='favorite_recipes')
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, related_name='favorited_by')

    class Meta:
        verbose_name = "Favorite Recipe"
        verbose_name_plural = "Favorite Recipes"
        unique_together = ['user', 'recipe']

    def __str__(self):
        return f"{self.user.username} -> {self.recipe.title}"

recipes/forms.py
# forms.py
from django import forms
from django.forms.models import inlineformset_factory
from .models import RecipeIngredient, Ingredient, Unit, Recipe

class RecipeIngredientForm(forms.ModelForm):
    ingredient_name = forms.CharField(max_length=100, label="Название ингредиента")
    unit = forms.ModelChoiceField(queryset=Unit.objects.all(), label="Единица измерения")

    class Meta:
        model = RecipeIngredient
        fields = ('ingredient_name', 'quantity', 'unit')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.instance and self.instance.pk:
            self.fields['ingredient_name'].initial = self.instance.ingredient.name
            self.fields['unit'].initial = self.instance.ingredient.unit

    def clean(self):
        cleaned_data = super().clean()
        ingredient_name = cleaned_data.get('ingredient_name')
        unit = cleaned_data.get('unit')
        if ingredient_name and unit:
            ingredient, created = Ingredient.objects.get_or_create(
                name=ingredient_name,
                defaults={'unit': unit}
            )
            cleaned_data['ingredient'] = ingredient
        return cleaned_data

    def save(self, commit=True):
        self.instance.ingredient = self.cleaned_data.get('ingredient')
        return super().save(commit=commit)

RecipeIngredientFormSet = inlineformset_factory(
    Recipe, RecipeIngredient,
    form=RecipeIngredientForm,
    extra=1,
    can_delete=True
)

recipes/views.py
from django.urls import reverse_lazy
from django.shortcuts import redirect, get_object_or_404
import random
from django.views.generic import (
    ListView, DetailView, CreateView, UpdateView, DeleteView
)
from .models import Unit, Category, Ingredient, Recipe
from .forms import RecipeIngredientFormSet


class HomeView(ListView):
    model = Recipe
    template_name = "recipes/index.html"
    context_object_name = "random_recipes"

    def get_queryset(self):
        queryset = super().get_queryset()
        # Преобразуем QuerySet в список и выбираем 3 случайных элемента
        random_recipes = random.sample(list(queryset), min(3, queryset.count()))
        return random_recipes


# Unit Views
class UnitListView(ListView):
    model = Unit
    template_name = "recipes/unit_list.html"
    context_object_name = "units"


class UnitCreateView(CreateView):
    model = Unit
    template_name = "recipes/unit_form.html"
    fields = ['name']
    success_url = reverse_lazy('recipes:unit-list')


class UnitUpdateView(UpdateView):
    model = Unit
    template_name = "recipes/unit_update_form.html"
    fields = ['name']
    success_url = reverse_lazy('recipes:unit-list')


class UnitDeleteView(DeleteView):
    model = Unit
    template_name = "recipes/unit_confirm_delete.html"
    success_url = reverse_lazy('recipes:unit-list')


# Category Views
class CategoryListView(ListView):
    model = Category
    template_name = "recipes/category_list.html"
    context_object_name = "categories"


class CategoryCreateView(CreateView):
    model = Category
    template_name = "recipes/category_form.html"
    fields = ['name', 'parent']
    success_url = reverse_lazy('recipes:category-list')


class CategoryUpdateView(UpdateView):
    model = Category
    template_name = "recipes/category_update_form.html"
    fields = ['name', 'parent']
    success_url = reverse_lazy('recipes:category-list')


class CategoryDeleteView(DeleteView):
    model = Category
    template_name = "recipes/category_confirm_delete.html"
    success_url = reverse_lazy('recipes:category-list')


# Ingredient Views
class IngredientListView(ListView):
    model = Ingredient
    template_name = "recipes/ingredient_list.html"
    context_object_name = "ingredients"


class IngredientCreateView(CreateView):
    model = Ingredient
    template_name = "recipes/ingredient_form.html"
    fields = ['name', 'unit']
    success_url = reverse_lazy('recipes:ingredient-list')


class IngredientUpdateView(UpdateView):
    model = Ingredient
    template_name = "recipes/ingredient_update_form.html"
    fields = ['name', 'unit']
    success_url = reverse_lazy('recipes:ingredient-list')


class IngredientDeleteView(DeleteView):
    model = Ingredient
    template_name = "recipes/ingredient_confirm_delete.html"
    success_url = reverse_lazy('recipes:ingredient-list')


# Recipe Views
class RecipeListView(ListView):
    model = Recipe
    template_name = "recipes/recipe_list.html"
    context_object_name = "recipes"
    paginate_by = 4

    def get_queryset(self):
        query = self.request.GET.get('q', '')
        queryset = Recipe.all_objects.filter(is_archived=False)
        if query:
            queryset = queryset.filter(title__icontains=query)
        category_id = self.request.GET.get("category")
        if category_id:
            queryset = queryset.filter(category__id=category_id)
        return queryset
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['query'] = self.request.GET.get('q', '')
        context['category'] = Category.objects.all()
        context['total_recipes'] = self.get_queryset().count()
        context['total_pages'] = context['paginator'].num_pages if context.get('paginator') else 1
        return context


class RecipeDetailView(DetailView):
    model = Recipe
    template_name = "recipes/recipe_detail.html"
    context_object_name = "recipe"


class RecipeCreateView(CreateView):
    model = Recipe
    template_name = "recipes/recipe_form.html"
    fields = [
        'title', 'description', 'instructions', 'cooking_time',
        'preparation_time', 'difficulty', 'servings', 'category', 
        'image', 'author'
    ]
    success_url = reverse_lazy('recipes:recipe-list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context['ingredients'] = RecipeIngredientFormSet(self.request.POST)
        else:
            context['ingredients'] = RecipeIngredientFormSet()
        return context

    def form_valid(self, form):
        # Устанавливаем автора рецепта
        form.instance.author = self.request.user
        self.object = form.save()
        context = self.get_context_data()
        ingredients = context['ingredients']
        if ingredients.is_valid():
            ingredients.instance = self.object
            ingredients.save()
        return super().form_valid(form)


class RecipeUpdateView(UpdateView):
    model = Recipe
    template_name = "recipes/recipe_form.html"
    fields = [
        'title', 'description', 'instructions', 'cooking_time',
        'preparation_time', 'difficulty', 'servings', 'category', 
        'image', 'author',
    ]
    success_url = reverse_lazy('recipes:recipe-list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context['ingredients'] = RecipeIngredientFormSet(self.request.POST, instance=self.object)
        else:
            context['ingredients'] = RecipeIngredientFormSet(instance=self.object)
        return context

    def form_valid(self, form):
        self.object = form.save()
        context = self.get_context_data()
        ingredients = context['ingredients']
        if ingredients.is_valid():
            ingredients.instance = self.object
            ingredients.save()
        return super().form_valid(form)


class RecipeDeleteView(DeleteView):
    model = Recipe
    template_name = "recipes/recipe_confirm_delete.html"
    success_url = reverse_lazy('recipes:recipe-list')


def recipe_restore(request, pk):
    recipe = get_object_or_404(Recipe.all_objects, pk=pk)
    recipe.is_archived = False
    recipe.save()
    return redirect('recipes:recipe-list')

recipes/templates/recipes/category_confirm_delete.html
{% extends "recipes/base.html" %}

{% block title %}
Удаление категории
{% endblock %}

{% block content %}
<h1>Удаление существующей категории</h1>
    <p>Вы уверены, что хотите удалить "{{ category.name }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Да</button>
    </form>
<a href="{% url 'recipes:category-list' %}">Назад к списку категорий</a>
{% endblock %}

recipes/templates/recipes/category_list.html
{% extends "recipes/base.html" %}

{% block title %}
Категории
{% endblock %}

{% block content %}
<h1>Категории</h1>
<a href="{% url 'recipes:category-create' %}">Создать категорию</a>
<ul>
    {% for category in categories %}
        <li>
            {{ category.name }} - 
            <a href="{% url 'recipes:category-update' category.id %}">Редактировать</a> | 
            <a href="{% url 'recipes:category-delete' category.id %}">Удалить</a>
        </li>
    {% endfor %}
</ul>
{% endblock %}

recipes/templates/recipes/category_update_form.html
{% extends "recipes/base.html" %}

{% block title %}
Редактирование категории
{% endblock %}

{% block content %}
<h1>Редактирование существующей категории</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Сохранить</button>
</form>
<a href="{% url 'recipes:category-list' %}">Назад к списку категорий</a>
{% endblock %}

recipes/templates/recipes/index.html
{% extends 'recipes/base.html' %}

{% block title %}
    Главная - Рецепты
{% endblock %}


{% block content %}
    <!-- Баннер -->
    <section class="bg-cover bg-center h-64 flex items-center justify-center text-white transition-all" style="background-image: url('https://source.unsplash.com/1600x900/?food');">
        <div class="bg-black bg-opacity-50 p-6 rounded-lg">
            <h2 class="text-3xl font-bold mb-4">Поделись своим рецептом!</h2>
            <a href="{% url 'recipes:recipe-create' %}">
            <button class="bg-yellow-500 text-white px-4 py-2 rounded-lg transition duration-150 hover:bg-yellow-600">Добавить свой рецепт</button>
            </a>
        </div>
    </section>
    
    <!-- Список рецептов -->
    <main class="container mx-auto my-8 px-4">
        <h2 class="text-2xl font-bold mb-4">Кушайте, не обляпайтесь!</h2>
        {% for recipe in random_recipes %}
        <div class="space-y-6">
            <!-- Карточка рецепта -->
                <div class="bg-white shadow-md rounded-lg flex p-4">
            {% if recipe.image %}
                <img src="{{ recipe.image.url }}" alt="{{ recipe.title }}" class="rounded-lg mr-4" width="250" height="200">
            {% else %}
                <div class="rounded-lg mr-4 w-32 h-32 bg-gray-200"></div> <!-- Заглушка, если изображения нет -->
            {% endif %}
            <div>
            <h3 class="text-xl font-bold"><a href="{% url 'recipes:recipe-detail' recipe.pk %}" class="text-blue-500 hover:underline">{{ recipe.title }}</a></h3>
            <p class="text-gray-600 line-clamp-3">{{ recipe.description }}</p>
            <p><strong>Автор:</strong> {{ recipe.author.username|default:"Unknown Author" }}</p>
            <a href="{% url 'recipes:recipe-detail' recipe.pk %}">
                <button class="mt-2 text-blue-500 hover:underline">Подробнее</button>
            </a>
            </div>
        </div>
        {% endfor %}
    </main>
{% endblock %}

recipes/templates/recipes/ingredient_confirm_delete.html
{% extends "recipes/base.html" %}

{% block title %}
Удаление ингредиента
{% endblock %}

{% block content %}
<h1>Удаление существующего ингредиента</h1>
    <p>Вы уверены, что хотите удалить "{{ ingredient.name }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Да</button>
    </form>
<a href="{% url 'recipes:ingredient-list' %}">Назад к списку ингредиентов</a>
{% endblock %}

recipes/templates/recipes/ingredient_form.html
{% extends "recipes/base.html" %}

{% block title %}
Создание ингредиента
{% endblock %}

{% block content %}
<h1>Создание нового ингредиента</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Сохранить</button>
</form>
<a href="{% url 'recipes:ingredient-list' %}">Назад к списку ингредиентов</a>
{% endblock %}

recipes/templates/recipes/ingredient_update_form.html
{% extends "recipes/base.html" %}

{% block title %}
Редактирование ингредиента
{% endblock %}

{% block content %}
<h1>Редактирование существующего ингредиента</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Сохранить</button>
</form>
<a href="{% url 'recipes:ingredient-list' %}">Назад к списку ингредиентов</a>
{% endblock %}

recipes/templates/recipes/recipe_confirm_delete.html
{% extends 'recipes/base.html' %}

{% block title %}
  Подтверждение удаления рецепта
{% endblock %}

{% block content %}
<div class="container mx-auto my-8 px-4">
  <h1 class="text-3xl font-bold mb-6">Удалить рецепт: "{{ object.title }}"</h1>
  
  <div class="bg-white shadow-md rounded-lg p-6">
    <p class="text-gray-700 mb-4">
      Вы уверены, что хотите удалить этот рецепт? Это действие необратимо.
    </p>
    <div class="flex space-x-4">
      <form method="post">
        {% csrf_token %}
        <button type="submit" class="bg-red-500 text-white px-4 py-2 rounded hover:bg-red-600">
          Удалить
        </button>
      </form>
      <a href="{% url 'recipes:recipe-detail' object.pk %}" class="bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600">
        Отмена
      </a>
    </div>
  </div>
</div>
{% endblock %}




<!-- 
<h1>Удаление существующего рецепта</h1>
    <p>Вы уверены, что хотите удалить "{{ recipe.title }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Да</button>
    </form>
<a href="{% url 'recipes:ingredient-list' %}">Назад к списку ингредиентов</a> -->

recipes/templates/recipes/recipe_form.html
{% extends 'recipes/base.html' %}
{% load widget_tweaks %}

{% block title %}
  {% if object %}
    Редактирование рецепта
  {% else %}
    Создание нового рецепта
  {% endif %}
{% endblock %}

{% block content %}
<div class="container mx-auto my-8 px-4">
  <h1 class="text-3xl font-bold mb-6">
    {% if object %}
      Редактирование рецепта
    {% else %}
      Создание нового рецепта
    {% endif %}
  </h1>
  <form method="post" enctype="multipart/form-data" class="bg-white shadow-md rounded-lg p-6">
    {% csrf_token %}
    <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
      <div>
        {{ form.title.label_tag }}
        {{ form.title|add_class:"w-full px-3 py-2 border border-gray-300 rounded" }}
      </div>
      <!-- Сложность -->
      <div>
        {{ form.difficulty.label_tag }}
        {{ form.difficulty|add_class:"w-full px-3 py-2 border border-gray-300 rounded" }}
      </div>
      <!-- Время приготовления -->
      <div>
        {{ form.cooking_time.label_tag }}
        {{ form.cooking_time|add_class:"w-full px-3 py-2 border border-gray-300 rounded" }}
      </div>
      <!-- Время подготовки -->
      <div>
        {{ form.preparation_time.label_tag }}
        {{ form.preparation_time|add_class:"w-full px-3 py-2 border border-gray-300 rounded" }}
      </div>
      <!-- Порции -->
      <div>
        {{ form.servings.label_tag }}
        {{ form.servings|add_class:"w-full px-3 py-2 border border-gray-300 rounded" }}
      </div>
      <!-- Категории -->
      <div>
        {{ form.category.label_tag }}
        {{ form.category|add_class:"w-full px-3 py-2 border border-gray-300 rounded" }}
      </div>
      <!-- Изображение -->
      <div class="md:col-span-2">
        {{ form.image.label_tag }}
        {{ form.image|add_class:"w-full px-3 py-2 border border-gray-300 rounded" }}
      </div>
      <!-- Описание -->
      <div class="md:col-span-2">
        {{ form.description.label_tag }}
        {{ form.description|add_class:"w-full px-3 py-2 border border-gray-300 rounded" }}
      </div>
      <!-- Инструкции -->
      <div class="md:col-span-2">
        {{ form.instructions.label_tag }}
        {{ form.instructions|add_class:"w-full px-3 py-2 border border-gray-300 rounded" }}
      </div>
      <!-- Автор -->
      <div class="hidden">
        {{ form.author }}
      </div>
    </div>

    <!-- Блок ингредиентов -->
    <h2 class="text-2xl font-bold mt-6 mb-4">Ингредиенты</h2>
    {{ ingredients.management_form }}
    {% for form in ingredients %}
      <div class="grid grid-cols-1 md:grid-cols-3 gap-4 mb-4 border p-4 rounded">
        <div>
          {{ form.ingredient_name.label_tag }}
          {{ form.ingredient_name|add_class:"w-full px-3 py-2 border border-gray-300 rounded" }}
        </div>
        <div>
          {{ form.quantity.label_tag }}
          {{ form.quantity|add_class:"w-full px-3 py-2 border border-gray-300 rounded" }}
        </div>
        <div>
          {{ form.unit.label_tag }}
          {{ form.unit|add_class:"w-full px-3 py-2 border border-gray-300 rounded" }}
        </div>
        {% if form.instance.pk %}
          <div class="md:col-span-3 flex items-center">
            {{ form.DELETE }}
            <span class="ml-2 text-red-500 text-sm">Удалить ингредиент</span>
          </div>
        {% endif %}
      </div>
    {% endfor %}

    <!-- Кнопки отправки и отмены -->
    <div class="flex items-center justify-between mt-6">
      <button type="submit" class="bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600">
        {% if object %}Сохранить изменения{% else %}Сохранить рецепт{% endif %}
      </button>
      <a href="{% url 'recipes:recipe-list' %}" class="text-blue-500 hover:underline">Отмена</a>
    </div>
  </form>
</div>
{% endblock %}

recipes/templates/recipes/recipe_list.html
{% extends 'recipes/base.html' %}

{% block title %}
    Все рецепты - Рецепты
{% endblock %}

{% block content %}
    <main class="container mx-auto my-8 px-4">
        <!-- Поиск -->
        <form method="GET" action="" class="mb-4">
            <input type="text" name="q" placeholder="Поиск рецепта..." value="{{ request.GET.q }}"
                   class="border border-gray-300 px-4 py-2 rounded-lg w-full">
            <button type="submit" class="mt-2 bg-blue-500 text-white px-4 py-2 rounded-lg hover:bg-blue-600">
                Найти
            </button>
        </form>
        
        <!-- Список рецептов -->
        <div class="space-y-6">
            {% for recipe in recipes %}
                <div class="bg-white shadow-md rounded-lg flex p-4">
                    {% if recipe.image %}
                        <img src="{{ recipe.image.url }}" alt="{{ recipe.title }}" class="rounded-lg mr-4" width="250" height="200">
                    {% else %}
                        <div class="rounded-lg mr-4 w-32 h-32 bg-gray-200"></div>
                    {% endif %}
                    <div>
                        <h3 class="text-xl font-bold">
                            <a href="{% url 'recipes:recipe-detail' recipe.pk %}" class="text-blue-500 hover:underline">
                                {{ recipe.title }}
                            </a>
                        </h3>
                        <p class="text-gray-600 line-clamp-3">{{ recipe.description }}</p>
                        <p><strong>Автор:</strong> {{ recipe.author.username|default:"Unknown Author" }}</p>
                        <a href="{% url 'recipes:recipe-detail' recipe.pk %}">
                            <button class="mt-2 text-blue-500 hover:underline">Подробнее</button>
                        </a>
                    </div>
                </div>
            {% empty %}
                <p class="text-gray-600">Рецепты не найдены.</p>
            {% endfor %}
        </div>
        
        <!-- Пагинация -->
        {% if is_paginated %}
        <div class="flex justify-center space-x-2 mt-4">
            {% if page_obj.has_previous %}
                <a href="?page=1&q={{ query }}" class="px-3 py-1 bg-gray-200 rounded">&laquo; Первая</a>
                <a href="?page={{ page_obj.previous_page_number }}&q={{ query }}" class="px-3 py-1 bg-gray-200 rounded">‹</a>
            {% endif %}

            <span class="px-3 py-1 bg-blue-500 text-white rounded">
                Стр. {{ page_obj.number }} из {{ total_pages }}
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}&q={{ query }}" class="px-3 py-1 bg-gray-200 rounded">›</a>
                <a href="?page={{ total_pages }}&q={{ query }}" class="px-3 py-1 bg-gray-200 rounded">Последняя &raquo;</a>
            {% endif %}
        </div>
    {% endif %}
    </main>
{% endblock %}

recipes/templates/recipes/unit_confirm_delete.html
{% extends "recipes/base.html" %}

{% block title %}
Удаление единиц
{% endblock %}

{% block content %}
<h1>Удаление существующих единиц</h1>
    <p>Вы уверены, что хотите удалить "{{ unit.name }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Да</button>
    </form>
<a href="{% url 'recipes:unit-list' %}">Назад к списку единиц</a>
{% endblock %}

recipes/templates/recipes/unit_form.html
{% extends "recipes/base.html" %}

{% block title %}
Создание единиц
{% endblock %}

{% block content %}
<h1>Создание новых единиц измерения</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Сохранить</button>
</form>
<a href="{% url 'recipes:unit-list' %}">Назад к списку единиц</a>
{% endblock %}

recipes/templates/recipes/unit_list.html
{% extends "recipes/base.html" %}

{% block title %}
Еденицы измерения
{% endblock %}

{% block content %}
<h1>Единицы измерения</h1>
<a href="{% url 'recipes:unit-create' %}">Add Unit</a>
<ul>
    {% for unit in units %}
        <li>
            {{ unit.name }} - 
            <a href="{% url 'recipes:unit-update' unit.id %}">Edit</a> | 
            <a href="{% url 'recipes:unit-delete' unit.id %}">Delete</a>
        </li>
    {% endfor %}
</ul>
{% endblock %}

recipes/templates/recipes/unit_update_form.html
{% extends "recipes/base.html" %}

{% block title %}
Редактирование единиц
{% endblock %}

{% block content %}
<h1>Редактирование существующих единиц измерения</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Сохранить</button>
</form>
<a href="{% url 'recipes:unit-list' %}">Назад к списку единиц</a>
{% endblock %}